Questionnaire's !
NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819 pull request #138
Opened 2019-05-19 18:01 UTC by XanderVeldeman

# Eindelijk die *F$@!?ing* vragen zijn af
# Je kan nu vragenlijsten invullen:
- Open vragen
![image](https://user-images.githubusercontent.com/25788097/57986027-e137cd80-7a6f-11e9-89ff-7399c083a917.png)

- Single choice
![image](https://user-images.githubusercontent.com/25788097/57985971-49d27a80-7a6f-11e9-9679-d3fdb28af5ae.png)

- Multiple choice (wel een slecht voorbeeld)
![image](https://user-images.githubusercontent.com/25788097/57985977-5951c380-7a6f-11e9-8048-5b83126220fc.png)

- Dropdown
![image](https://user-images.githubusercontent.com/25788097/57985983-640c5880-7a6f-11e9-9850-a5980478fcba.png)

- Email
![image](https://user-images.githubusercontent.com/25788097/57986010-ba799700-7a6f-11e9-9822-91c7e7673766.png)

- En natuurlijk een bericht als je de vragenlijst hebt ingevult
![image](https://user-images.githubusercontent.com/25788097/57985992-82725400-7a6f-11e9-8c94-a771fa80d69c.png)

# Vragenlijsten beheren
![image](https://user-images.githubusercontent.com/25788097/57986033-02002300-7a70-11e9-9a8b-31c2da14ed4e.png)
**Hier kan je:**
- Vragenlijsten aanpassen bv tags
![image](https://user-images.githubusercontent.com/25788097/57986045-1c3a0100-7a70-11e9-93a5-879fbdec834e.png)
- Resultaten van vragen bekijken
Text-based:
![image](https://user-images.githubusercontent.com/25788097/57986053-307dfe00-7a70-11e9-9077-4ee45d169e12.png)
Choice-based:
![image](https://user-images.githubusercontent.com/25788097/57986070-573c3480-7a70-11e9-8f83-166311ae1845.png)

# Party Parrot
Ook heb ik volgende party parrot op de about page geplaatst
![party](https://cultofthepartyparrot.com/parrots/hd/ceilingparrot.gif)

En nu wachten tot de Code-`insert type of warrior` mijn hoofd afhakt.
![me](https://media.giphy.com/media/Oj5w7lOaR5ieNpuBhn/giphy.gif)

2019-05-19 19:21 UTC, NielsSensei requested changes
Helaas moet ik de boeman spelen om volgende reden:

- De app crasht hard als ik als anonieme gebruiker de vragenlijst wil invullen en dit dan ook gedaan heb.
- De app crasht als ik een verplichte vraag niet invul maar hij valideert hier niet op voor de publish.
(sommige modals zijn nog dat beetje engels)

Nu naar de fluff opmerkingen:
- Ik weet niet of het mogelijk is om dezelfde questionnaire meermaals in te vullen:
![image](https://user-images.githubusercontent.com/44059248/57986903-ecdcc180-7a7a-11e9-979c-34f161939ea2.png)

- Bij aanmaak questionnaire ziet 0,00% er properder uit hiero
![image](https://user-images.githubusercontent.com/44059248/57986911-0c73ea00-7a7b-11e9-8421-04f2150858c0.png)

- er enkel bij zorgen dat de options form getoond wordt als we een multipleanswer dingen kiezen
![image](https://user-images.githubusercontent.com/44059248/57986923-3b8a5b80-7a7b-11e9-8b6b-d88ab57841df.png)

- Naast van het feit dat je authorizatie een andere keer wou doen, miss een redirect na wijzigingen opslaan?
![image](https://user-images.githubusercontent.com/44059248/57986930-51981c00-7a7b-11e9-999f-922b432188e7.png)

- boeman out
![boeman](https://media2.giphy.com/media/Aul0U9qe8Ocrm/giphy.webp?cid=790b76115ce1ac0c635765523647f106&rid=giphy.webp)

2019-05-20 14:05 UTC, NielsSensei requested changes
-Dropvragen hebben een placeholder nodig
![image](https://user-images.githubusercontent.com/44059248/58027506-0df3ef80-7b19-11e9-8a52-8a27a1b91acd.png)

- NAN problem van hierboven is nog niet opgelost

2019-05-20 15:00 UTC, XanderVeldeman commented
![image](https://user-images.githubusercontent.com/25788097/58031461-c4a79e00-7b20-11e9-99a6-299f7f861aa3.png)
Fixed

2019-05-20 15:52 UTC, NielsSensei approved these changes

2019-05-20 15:53 UTC, merged